-- city names, their respective lengths
SELECT CITY, LENGTH(CITY)
FROM STATION
-- the shortest and longest city names
WHERE CITY = (SELECT CITY FROM STATION ORDER BY LENGTH(CITY) DESC, CITY LIMIT 1)
    OR CITY = (SELECT CITY FROM STATION ORDER BY LENGTH(CITY), CITY LIMIT 1)
